=== l3miage-bouvier5/TuxLetterGame_template/src/data/XSD/hiscores.xsd
<?xml version="1.0"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->

<!-- Ce fichier XML Schema a pour but de structurer le fichier hiscores.xml
     qui va afficher les meilleurs scores parmis tous les joueurs.
     
     auteurs : Bouvier LÃ©o Delagrange Alex
-->



<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://myGame/tux"
           xmlns:tux="http://myGame/tux"
           elementFormDefault="qualified">
    
    <xs:element name="hiscores" type="tux:Hiscores"/>
    <xs:complexType name="Hiscores">
        <xs:sequence>
            <xs:element name="partie" type="tux:Partie" maxOccurs = "unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="Partie">
        <xs:sequence>
            <xs:element name="nom" type ="xs:string"/>
            <xs:element name="avatar" type="xs:string"/>
            <xs:element name="mot" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="score" type="xs:int"/>
        <xs:attribute name="date" type="xs:string"/>   
    </xs:complexType>

    
</xs:schema>

=== l3miage-bouvier5/TuxLetterGame_template/build/classes/data/xml/hiscores.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<hiscores xmlns="http://myGame/tux" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://myGame/tux ../xsd/hiscores.xsd">
    <partie date="2022-12-06" score="364">
        <nom>julien</nom>
        <avatar>../images/venom.jpg</avatar>
        <mot>ventouse</mot>
    </partie>
<partie date="2022-12-06" score="230">
        <nom>boyb</nom>
        <mot>coloriage</mot>
        <avatar>../images/jafar.jpg</avatar>
    </partie>
<partie date="2022-12-06" score="350">
        <nom>bob</nom>
        <mot>telescope</mot>
        <avatar>../images/walter-white.jpg</avatar>
    </partie>
<partie date="2022-12-06" score="230">
        <nom>jule</nom>
        <mot>etudiant</mot>
        <avatar>../images/jafar.jpg</avatar>
    </partie>
<partie date="2022-12-06" score="210">
        <nom>jule</nom>
        <mot>anniversaire</mot>
        <avatar>../images/jafar.jpg</avatar>
    </partie>
<partie date="2022-12-06" score="106">
        <nom>jule</nom>
        <mot>manger</mot>
        <avatar>../images/jafar.jpg</avatar>
    </partie>
<partie date="2022-12-06" score="110">
        <nom>bob</nom>
        <mot>matin</mot>
        <avatar>../images/walter-white.jpg</avatar>
    </partie>
<partie date="2022-12-06" score="200">
        <nom>isfs</nom>
        <mot>serendipite</mot>
        <avatar>../images/jafar.jpg</avatar>
    </partie>
<partie date="2022-12-06" score="196">
        <nom>bob</nom>
        <mot>appareil</mot>
        <avatar>../images/walter-white.jpg</avatar>
    </partie>
<partie date="2022-12-06" score="180">
        <nom>fh</nom>
        <mot>maison</mot>
        <avatar>../images/joker.jpg</avatar>
    </partie>
</hiscores>
