=== l3miage-bouvier5/TuxLetterGame_template/build/classes/data/XSD/dico.xsd
<?xml version="1.0"?>

<!--
 *
 * @author bouvier et delagrange
-->

<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:tux="http://myGame/tux"
           targetNamespace="http://myGame/tux"
           elementFormDefault="qualified">
    
    
    <xs:element name="dictionnaire" type="tux:Dictionnaire"/>
    <xs:complexType name="Dictionnaire">
        <xs:sequence>
            <xs:element name="niveau" type="tux:Niveau"/>
        </xs:sequence>
        
    </xs:complexType>
    <xs:complexType name="Niveau">
        <xs:sequence>
            <xs:element name="mot" type="tux:Mot"/>  
        </xs:sequence>
        <xs:attribute name="numero" type="tux:Numero"/>
                      
    </xs:complexType>
    <xs:simpleType name="Mot">
        <xs:restriction base="xs:string">
            <xs:minLength value="3"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="Numero">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="5"/>
        </xs:restriction>
    </xs:simpleType>
           
</xs:schema>

=== l3miage-bouvier5/TuxLetterGame_template/build/classes/data/xml/dico.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
 *
 * @author bouvier et delagrange
--><dictionnaire xmlns="http://myGame/tux" xmlns:xsi="http://www.w3.org/2001/XMLSchema-Instance" xsi:schemaLocation="http://myGame/tux ../xsd/dico.xsd">
    
    <niveau numero="1">
        <mot>deux</mot>
        <mot>oui</mot>
        <mot>soeur</mot>
        <mot>jouet</mot>
        <mot>papa</mot>
        <mot>sac</mot>
        <mot>non</mot>
        <mot>mer</mot>
        <mot>lac</mot>
        <mot>amis</mot>
    </niveau>

    <niveau numero="2">
        <mot>trois</mot>
        <mot>maths</mot>
        <mot>livre</mot>
        <mot>porte</mot>
        <mot>fille</mot>
        <mot>garcon</mot>
        <mot>arbre</mot>
        <mot>ecole</mot>
        <mot>route</mot>
        <mot>manger</mot>
        <mot>matin</mot>  
</niveau>

    <niveau numero="3">
        <mot>ascenceur</mot>
        <mot>maison</mot>
        <mot>voiture</mot>
        <mot>fenetre</mot>
        <mot>poubelle</mot>
        <mot>grillage</mot>
        <mot>chemin</mot>
        <mot>batiment</mot>
        <mot>legumes</mot>
        <mot>descendre</mot>
        <mot>escalier</mot>
        <mot>appareil</mot>
</niveau>
    
    <niveau numero="4">
        <mot>serendipite</mot>
        <mot>anniversaire</mot>
        <mot>coloriage</mot>
        <mot>vacances</mot>
        <mot>ambulance</mot>
        <mot>rhinoc√©ros</mot>
        <mot>banquette</mot>
        <mot>escabeau</mot>
        <mot>etudiant</mot>
        <mot>incendie</mot>
        <mot>extincteur</mot>
</niveau>
    
    <niveau numero="5">
        <mot>halieutique</mot>
        <mot>xylophone</mot>
        <mot>jugulaire</mot>
        <mot>chromosome</mot>
        <mot>artistiquement</mot>
        <mot>terrorisme</mot>
        <mot>escalator</mot>
        <mot>ventouse</mot>
        <mot>telescope</mot>
        <mot>cyclone</mot>
        <mot>photocopieuse</mot>
    </niveau>
</dictionnaire>
